name: Restrict Issue Creation

on:
  issues:
    types: [opened]

jobs:
  close_unwanted_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Close issue if opened by someone else
      if: github.event.issue.user.login != 'Flartiny'
      run: |
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state":"closed", "body":"Sorry, only the repository owner can open issues."}'
